name: nextfold-dev
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.3.1
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - cython
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - pydantic
  - pip:
      - build
      - pre-commit
      - python-dotenv
