# Jumper et al. (2021) Suppl. Table 5, Model 1.1.1

defaults:
  - alphafold_monomer_shared
  - _self_

data:
  common:
    max_extra_msa: 5120
    reduce_msa_clusters_by_max_templates: true
    use_templates: true

model:
  embeddings_and_evoformer:
    template:
      embed_torsion_angles: true
      enabled: true
  heads:
    predicted_aligned_error: null

globals:
  name: alphafold_model_1
