# Jumper et al. (2021) Suppl. Table 5, Model 1.1.4

defaults:
  - alphafold_monomer_shared
  - _self_

data:
  common:
    max_extra_msa: 5120

model:
  heads:
    predicted_aligned_error: null

globals:
  name: alphafold_model_4
